### ISSUE TITLE
页面初次加载相关问题请教

### ISSUE THREAD

**Issue by Anthony-Ghy** [mayu888/lazylist-react#1]
您好麻烦问下就是我在使用您这个组件的时候页面首次加载商品卡片是一个一个弹出来【比如页面可是区域是四个商品卡片】，虽然说时间很迅速，但是还是想请教一下是否可以通过哪种方式让页面首次加载的时候在可视区域的卡片一起显示出来呢，十分感谢！

**Comment by Anthony-Ghy** [comment]
同时想请教一下在手机浏览器里面由于我使用的是session存储页面滚动的高度，比如滚动了1000，但是当我点击一个商品卡片进到详情页以后在返回回来，根据您的这个组件的话只展示可视区域的卡片，那整个页面如果只开始展示四个的话相当于我滚动的高度的那部分没有被撑开，也就不会滚动到相应的距离，这个问题想请教一下怎么解决呢，十分感谢！

**Comment by mayu888** [comment]
> 您好麻烦问下就是我在使用您这个组件的时候页面首次加载商品卡片是一个面板来【显示页面可是区域是四个商品卡片】，虽然说时间很迅速，但是还是想请教一下是否可以通过最早的方式让页面首次加载的时候在可视区域的卡片一起显示出来呢，十分感谢！
组件有一个**renderCount**属性，指定每次渲染的数量。

**Comment by mayu888** [comment]
> 同时想请教一下在手机浏览器里面由于我使用的是session存储页面滚动的高度，比如滚动了1000，但是当我点击一个商品卡片进到详情页以后在返回回来，根据您的这个组件的话只展示可视区域的卡片，那整个页面如果只开始展示四个的话相当于我滚动的高度的那部分没有被撑开，也就不会滚动到相应的距离，这个问题想请教一下怎么解决呢，十分感谢！

从列表页进入详情页时列表页应该是卸载了，当你在返回列表页后，列表页的内容重新加载，组件肯定会重新渲染，所以不能滚动到你指定的高度。不过我可以提供一个思路，就是根据session里有没有被记录的高度来指定渲染数量**renderCount**

**Comment by Anthony-Ghy** [comment]
感谢您的指点！我觉得我还有一些问题所以想问可否加下微信后续跟您请教下，麻烦啦


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mayu888/lazylist-react"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月19日(星期二) 上午10:53
收件人:&nbsp;"mayu888/lazylist-react"<lazylist-react@noreply.github.com&gt;;
抄送:&nbsp;"Anthony"<913406713@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mayu888/lazylist-react] 页面初次加载相关问题请教 (#1)





  
同时想请教一下在手机浏览器里面由于我使用的是session存储页面滚动的高度，比如滚动了1000，但是当我点击一个商品卡片进到详情页以后在返回回来，根据您的这个组件的话只展示可视区域的卡片，那整个页面如果只开始展示四个的话相当于我滚动的高度的那部分没有被撑开，也就不会滚动到相应的距离，这个问题想请教一下怎么解决呢，十分感谢！
  
从列表页进入详情页时列表页应该是卸载了，当你在返回列表页后，列表页的内容重新加载，组件肯定会重新渲染，所以不能滚动到你指定的高度。不过我可以提供一个思路，就是根据session里有没有被记录的高度来指定渲染数量renderCount

**Comment by Anthony-Ghy** [comment]
好的多谢！同时想问下就是我把您这个组件库clone下来以后运行npm run start 报错信息为：(babel plugin) Error:   .value is not a valid Plugin property 麻烦问下这个问题怎么解决呢

**Comment by mayu888** [comment]
> 好的多谢！同时想问下就是我把您这个组件库clone下来以后运行npm run start 报错信息为：(babel plugin) Error: .value is not a valid Plugin property 麻烦问下这个问题怎么解决呢

因为我还没有完善测试用例，后续会进行完善

**Comment by Anthony-Ghy** [comment]
好的大佬，后续会持续关注您这个组件，跟您学习一波怎么实现的。如果方便的话可否加个联系方式呢？
