### ISSUE TITLE
About rendering problem

### ISSUE THREAD

**Issue by resulturan** [mayu888/lazylist-react#2]
Hi, I am using your library for about 2 months and now I am stuck on something. I am listing an image list and after first rendering, I am updating the items on the list. The list is updated but items are not. What can be the reason for that?

![image](https://user-images.githubusercontent.com/81697915/157472687-4eae2bc4-759f-4ae0-8734-95c2b59da23d.png)

**Comment by mayu888** [comment]
1. Determine if shouldComponentupdate is used

**Comment by mayu888** [comment]
1. Determine if shouldComponentupdate is used
2. Determine if the key changes with the item

**Comment by mayu888** [comment]
1. Determine if shouldComponentupdate is used
2. Determine if the key changes with the item，because I made a strong comparison of props 
3. If none of the above, list the more detailed data, along with the code~

**Comment by resulturan** [comment]
Actually, I am listing at least 2000 images and some information on the screen. After that user is uploading a file and some image Infos are changing. images remain the same but some fields are changing. The changing fields are not rendered.

**Comment by mayu888** [comment]
I guess it's due to a problem with the key value，Will the **imageId** change after the user uploads the information?

**Comment by mayu888** [comment]
ok,i see,I'll release an alpha version later to fix this, you can use this version, within a week I'll fix it completely, it's going to be an official version

**Comment by mayu888** [comment]
Thanks for providing this bug!

**Comment by mayu888** [comment]
now you can install   lazylist-react@2.4.0-alpha.0.1

**Comment by resulturan** [comment]
Actually, the problem continues. I am sure the key is changing but changes are not rendered.

![image](https://user-images.githubusercontent.com/81697915/157622513-9fc6f36d-0f6a-46f3-89b1-5da349f3d9ea.png)
![image](https://user-images.githubusercontent.com/81697915/157622520-94e95868-e5c9-45c6-bf58-5bc4872a9ee8.png)

**Comment by NeuralMayu** [comment]
You try to reduce the length of the data, say 80 pieces of data, and then modify one of them, do you re-render it? And can you give me a few samples from imageList?

**Comment by resulturan** [comment]
It is working properly with 80 pieces of data. I think you are controlling props conditionally. Can you make it optional or make dynamic this length with proper props?

**Comment by NeuralMayu** [comment]
lazylist-react@2.4.0-alpha.0.2  has published
